FROM ubuntu:24.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    snort \
    snort-rules-default \
    tcpdump \
    libpcap-dev \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/log/snort /etc/snort/rules

ENTRYPOINT ["snort"]
CMD ["-V"]
